services:
    # ...
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Document\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Category, group: Blog }
            
    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Document\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Blog post,group: Blog }
            
    